system:
  app_name: Dziennik Treningowy
  version: 1.0
paths:
  data_dir: /home/janek/Dokumenty/my/training_notebook/outputs
  blocks_dir: app/templates/blocks
block_names:
  table: Tabela serii
  list: Lista punktowa
  notes: Tekst
  metadata: Metadane
  deprecated: Przestarzały element
  text_1: Nagłówek H1
  text_2: Nagłówek H2
  text_3: Nagłówek H3
  text_4: Nagłówek H4
database:
  system_items: |-
    Wyciskanie sztangi leżąc, klatka, sztanga
    Martwy ciąg, plecy, sztanga
    Przysiady ze sztangą, nogi, sztanga
    Wyciskanie żołnierskie, barki, sztanga
    Podciąganie na drążku, plecy, własna masa
    Pompki z obciążeniem oburącz, klatka, własna masa
  user_items: |-
    Ulubione pompki z obciążeniem, klatka
    Sprinty pod górę, kondycja
    Nowe,brak,brak
    Hej,brak,sztanga
options:
  units: x, kg, lbs, km, m, s, min, h, %, bpm, kcal
